load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
  name = "invitee_as_remote",
  srcs = [
    "invitee_as_remote.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "inviter_as_remote",
  srcs = [
    "inviter_as_remote.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "inviter_as_remote_block_on_acceptance",
  srcs = [
    "inviter_as_remote_block_on_acceptance.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "child_as_receiver_and_callback",
  srcs = [
    "child_as_receiver_and_callback.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "child_as_queued_handle_sender",
  srcs = [
    "child_as_queued_handle_sender.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "child_as_handle_sender",
  srcs = [
    "child_as_handle_sender.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "child_sends_accept_invitation_pipe_to_parent",
  srcs = [
    "child_sends_accept_invitation_pipe_to_parent.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "child_sends_send_invitation_pipe_to_parent",
  srcs = [
    "child_sends_send_invitation_pipe_to_parent.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "child_sends_two_pipes_to_parent",
  srcs = [
    "child_sends_two_pipes_to_parent.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
cc_binary(
  name = "pass_pipe_back_and_forth",
  srcs = [
    "pass_pipe_back_and_forth.cc",
  ],
  deps = [
    "@base//base",
    "//mage/public",
    "//mage/test/magen:include",
  ],
  visibility = ["//visibility:public"],
)
